# Generated by setup.sh - update with your actual values or run the wizard
bucket       = "ORGPREFIX-tfstate-stage-123456789012-us-east-1"
key          = "stage/storage/terraform.tfstate"
region       = "us-east-1"
encrypt      = true
use_lockfile = true
