name: "Terraform"
description: "Reusable composite action for Terraform operations"

inputs:
  working-directory:
    description: "Directory containing Terraform configuration"
    required: true
  action:
    description: "Terraform action: plan, apply, destroy"
    required: true
    default: "plan"
  backend-config:
    description: "Path to backend.hcl file (relative to working-directory)"
    required: false
    default: "backend.hcl"
  var-file:
    description: "Path to tfvars file (relative to working-directory)"
    required: false
    default: ""
  terraform-version:
    description: "Terraform version to use"
    required: false
    default: "1.14.x"
  aws-role-arn:
    description: "AWS IAM role ARN to assume"
    required: true
  aws-region:
    description: "AWS region"
    required: true
  skip-backend:
    description: "Skip backend configuration (for initial bootstrap)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: Terraform Init (with backend)
      if: inputs.skip-backend == 'false'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform init -backend-config="${{ inputs.backend-config }}" -input=false

    - name: Terraform Init (no backend)
      if: inputs.skip-backend == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform init -backend=false -input=false

    - name: Terraform Plan
      if: inputs.action == 'plan'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -n "${{ inputs.var-file }}" ]; then
          terraform plan -var-file="${{ inputs.var-file }}" -input=false
        else
          terraform plan -input=false
        fi

    - name: Terraform Apply
      if: inputs.action == 'apply'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -n "${{ inputs.var-file }}" ]; then
          terraform apply -var-file="${{ inputs.var-file }}" -auto-approve -input=false
        else
          terraform apply -auto-approve -input=false
        fi

    - name: Terraform Destroy
      if: inputs.action == 'destroy'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -n "${{ inputs.var-file }}" ]; then
          terraform destroy -var-file="${{ inputs.var-file }}" -auto-approve -input=false
        else
          terraform destroy -auto-approve -input=false
        fi
