# Generated by setup.sh - update with your actual values or run the wizard
env                 = "prod"
org_prefix          = "example"
expected_account_id = "123456789012"

primary_region  = "us-east-1"
allowed_regions = ["us-east-1"]

assume_role_arn = null
aws_profile     = null

example_bucket_suffix = ""

extra_tags = {}
