# Template for bootstrap backend configuration.
# Generated by setup.sh - do not edit manually.
bucket       = "${ORG_PREFIX}-tfstate-${ENV}-${ACCOUNT_ID}-${REGION}"
key          = "bootstrap/terraform.tfstate"
region       = "${REGION}"
encrypt      = true
use_lockfile = true
